### ISSUE TITLE
How to prevent data loss after user reload web page?

### ISSUE THREAD

**Issue by thammapat** [bradwellsb/blazor-service-samples#2]
I've try your project but when reload(F5) all data will be lost.  Is there anyway?

**Comment by bradwellsb** [comment]
This is expected behavior, as scoped services are scoped to the SignalR connection. When a user reloads the page, a new connection is created, so the service will be reconstructed by DI. Here's a section from the docs that explains more about [service lifetimes in Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-7.0#service-lifetime).

Depending on your use case, writing to your browser's localstorage might be a way to preserve data across page reloads. [This article](https://wellsb.com/csharp/aspnet/blazor-write-to-localstorage) is a bit outdated, but it should get you off to a good start. Let me know if you have any further questions

**Comment by thammapat** [comment]
Thank you for your reply, I will choose localstorage in this case.
